### ISSUE TITLE
Nice simple tool

### ISSUE THREAD

**Issue by ghostsquad** [mikepianka/drsz#1]
This is a great simple tool. I was wondering if you would be interested in extending the functionality of this and writing tests?

**Comment by mikepianka** [comment]
I mainly wrote it to just get more familiar with Go, but it wouldn't hurt to at least add some testing because it is a useful utility. What other functionality did you have in mind?

**Comment by ghostsquad** [comment]
I need the practice too, and I've been looking for a reason to dig more into Bubbletea and some of the other TUI libs out there, but I'm afraid when I first started, I bit off more than I could chew, and I got discouraged. A small utility like this could have the perfect scope for making a small interactive TUI tool.

If course, you would want to allow someone to choose how to use it, so introducing argument parsing would be needed.

**Comment by mikepianka** [comment]
Gotcha. It just being a simple CLI is good enough for the use case I had in mind. Some richer terminal output might be nice, but I don't think I would spend the time on a full TUI personally. If you come up with something and want to open a PR I'd be happy to take a look.
